### ISSUE TITLE
Differences between PixelTCN and PixelShuffle? 

### ISSUE THREAD

**Issue by HolmesShuan** [xiao9aba2008/DilatedPixelCNN#51]
PixelShuffle refers to `Real-Time Single Image and Video Super-Resolution Using an Efficient Sub-Pixel Convolutional Neural Network` by Shi et. al (2016). Thanks in advance.

**Comment by HongyangGao** [comment]
To my understanding, PixelShuffle is like the operation of transposed convolution. To upsample input by a factor of 2, it generates 4 outputs and combine them together using PixelShuffle.

For our method PixelTCN, we put some dependencies when generating these 4 outputs such that there are some relationships between adjacent pixels in the final layer output.

**Comment by HolmesShuan** [comment]
PixelShuffle is similar/same to 2D deconvolution in Figure 3, right? PixelTCN combines both low-resolution info and reconstructed high-resolution info to generate the adjacent pixels. It is convincing for me. But I still wonder why PixelTCN outperforms `PixelShuffle+Nonlinear(e.g., ReLU)+Conv 3x3`. A little hint?

**Comment by HongyangGao** [comment]
I think it is because we explicitly impose structure information in PixelTCN. When performing upsampling tasks, the adjacent pixels may be close to each other especially on natural images. Our method explicitly build such kind of dependencies among them.

While for PixelShuffle+Nonlinear(e.g., ReLU)+Conv 3x3, there is no such structure here. With abundant data and perfect training, this can learn the structure finally. But in practice, overfitting and other problems make it hard to learn such kind of structure information. You can consider the relationship between convolution layer and fully-connected layer. Ideally, fully-connected layer is more powerful than convolution layer. The locality structure in convolution layer makes it more popular especially when data and training are not in perfect situation.

Hope this explanation helps you.

**Comment by HolmesShuan** [comment]
It makes sense. Thanks. I will consider rewriting PixelTCN in PyTorch.
